### ISSUE TITLE
채팅금지플러그인

### ISSUE THREAD

**Issue by qaw13** [if-Team/PMMP-Plugins#10]
포럼에있는건다안되가지구.. command: /mute 닉네임(해당유저를벙어리시킵니다)
/unmute 닉네임 (해당유저벙어리를풀어줍니다)
/allmute(OP외에모든사람채팅을차단시킵니다)
/allunmute (채팅차단을해제합니다)
이런플러그인한번써보고싶네요

**Comment by ns827** [comment]
위시리스트 페이지가 **떡하니** 존재하네요.

https://github.com/if-Team/PMMP-Plugins/issues/2


......
