### ISSUE TITLE
월드에딧 플러그인

### ISSUE THREAD

**Issue by Xesame** [if-Team/PMMP-Plugins#13]
pc와 동일하게 '나무도끼(wand)'를 사용하는 월드에딧 플러그인 만들어주셧으면 합니다. 기존에있던 worldeditart는 사용할수있는 명령어 종류가 worldedit보다 적고 불편해서 요청 올립니다

**Comment by ChalkPE** [comment]
새 이슈 만드지 마시고 #2 에다가 올리세요
