### ISSUE TITLE
아이템케이스

### ISSUE THREAD

**Issue by childcovo** [if-Team/PMMP-Plugins#14]
아이템케이스부탁드립니다.
이코노미연동
상점 및 파는상점 생성시 유리가 그위에있으면 생성해주는그런거

**Comment by panda37** [comment]
음...여기올리시면안되고 데베님이 사정상 지운걸로알고있습니다

**Comment by ChalkPE** [comment]
여기다 하지 마시고 이슈 #2로 가세요

**Comment by ns827** [comment]
계속 잘못된 행동을 하실 경우 차단될 수 있습니다.
