### ISSUE TITLE
월드에딧 플러그인

### ISSUE THREAD

**Issue by Xesame** [if-Team/PMMP-Plugins#19]
나무도끼를 사용하는 월드에딧 프로그램을 만들어주셨으면 합니다. 기존에있던 Worldeditart는 좌표 설정이 불편하고 만들 수 있는 구조물이 제한되어 있습니다

명령어
나무도끼로 부수기: pos1설정
나무도끼로 터치: pos2 설정
//set <블럭코드>
-

**Comment by HmHmmHm** [comment]
좋네요, 마침 개발해보려했는데,
한번 진행해볼게요!
(*다른 분들 이 이슈 닫지 말아주세요*)

**Comment by HmHmmHm** [comment]
<H1>WorldEditK 작업 TODO</H1>

- [ ] //set
- [ ] //copy
- [ ] //cut
- [ ] //paste

**Comment by cloud9350** [comment]
@Xesame 흠님이 플러그인을 개발하실때까지 유용하게 쓰실 수 있는 WorldEdit 입니다.(!)
Feature으로는 pos1 pos2 set replace copy paste wand 등등..
http://www.youtube.com/watch?v=I_CMpOazGJY

**Comment by HmHmmHm** [comment]
우유맛비누님 프로젝트에서 이미 진척이 매우 진행된 상황이여서 작업폐기
