### ISSUE TITLE
엔티티가 움직이는 플러그인!

### ISSUE THREAD

**Issue by tutese** [if-Team/PMMP-Plugins#26]
hm님이 플긴겟에 올린 공지글중에서 엔티티가 움직이는 플긴은 게시글이 사라지고 없다고 뜨더군요... 다른건 다 좋은데 PMMP는 엔티티이동때문에 정말 불편합니다... hm님! 엔티티가 움직일 수 있게하는 플러그인 부탁드립니다~!

**Comment by ns827** [comment]
제-발 #2 에 써주세요

개발자 암걸려요... ㅠ
