### ISSUE TITLE
CreativeEconomy에 작은 오류가 있습니다.

### ISSUE THREAD

**Issue by lhb5407** [if-Team/PMMP-Plugins#27]
marketPrice.yml에 금이간 석재 벽돌 이 98.2가 맞으나 99.2로 기본설정되어있어 금이간 석재벽돌상점 만드려고 /창조경제 생성 98.2을 치면 코드를 찾을수 없다고 나옵니다 . 버전을 업데이트 하거나 수정하여 사용하라는 말을 해야할꺼 같습니다.

**Comment by lhb5407** [comment]
그리고 구매나 판매할때 /구매or판매 <수량> 을 써야 하지않습니까? 만약 두쌧 46개 있다면 게임을 하고있는데 64+64+46=174라는 계산을 머릿속으로 해야하는거 아닙니까? 그래서 생각한게 / 판매or구매 all 을 치면 가지고있는 모든 아이템을 모두 한번에 팔수 있게 하느겁니다.

**Comment by lhb5407** [comment]
좋은 생각이 아닙니까?

**Comment by ChalkPE** [comment]
에러 리포트는 #1 로 가시고
아이디어는 #2 로 가세요

**Comment by HmHmmHm** [comment]
@lhb5407 확인했습니다, 이후 버전에서 패치될 예정
(에러리포트 페이지는 별도로 만들지 마세요)
