### ISSUE TITLE
무제한 광산, 심플 에리어 오류

### ISSUE THREAD

**Issue by SkYDX** [if-Team/PMMP-Plugins#28]
-무제한 광산을 설정해놓고 돌을 캐면 다시 복구가 안됨
다시 돌을 채워넣으면 다시 되긴하지만 서버를 껐다 다시 키면 이 현상 반복

-화이트월드 설정을 해놓았는데 오피말고 오피아닌 사람이 블럭파괴 가능(알람이 뜨지만 블럭이 부서짐)

제발 도와주세요 ㅠ ㅠ

**Comment by ns827** [comment]
#1
