### ISSUE TITLE
SimpleArea보호오류

### ISSUE THREAD

**Issue by qaw13** [if-Team/PMMP-Plugins#3]
/sa whiteworld할시캐지거나설치가능이되는오류. 계속영역이겹친다는오류가있습니다 코드번호4아닌데 계속 영역이겹쳐있습니다ID:4이러면서보니깐콘솔에오류가..크래쉬덤프는안뜨나콘솔에뜹니다[Server] 08:45:39 [CRITICAL] Unhandled exception executing command 'sa make' in sa: Undefined index: ko-have-you-need-overlap-clear
[Server] 08:45:39 [NOTICE] ArrayOutOfBoundsException: "Undefined index: ko-have-you-need-overlap-clear" (E_NOTICE) in "/SimpleArea_v0_13-alpha.phar/src/SimpleArea/SimpleArea" at line 111

**Comment by HmHmmHm** [comment]
사용전 plugins/SimpleArea 폴더를 모두삭제해주세요.
 언어 설정에서 추가된 내용이 자동으로 변경되지 않고 있네요

**Comment by HmHmmHm** [comment]
@qaw13 심플에리어 0.14 업데이트되었습니다.
