### ISSUE TITLE
저기... 이번에 SimpleArea 판매오류입니다 ㅠㅠㅠ

### ISSUE THREAD

**Issue by radic2682** [if-Team/PMMP-Plugins#4]
일단... 방법이 맞는 지 확인할께요..
제가 이해하기론 op가 (/영역생성)으로 땅을 생성한 뒤 (/영역판매)를 해두면 플레이어가 땅을 살 수 있게 땅을 만들 수 있지요.... 맞지요? 여기까지...

자... 맞다면 (/영역생성)으로 땅을 생성에 성공했습니다. 하지만 (/영역판매)를 누르면 터미널에 다음과 같은 오류가 잡히네요... 그러면서 팔아집니다... 하지만 플레이어가 땅을 사거나 땅목록을 열어도 보이지 않네요..
[CRITICAL] Unhandled exception executing command '영역구매' in 영역구매: Undefined offset: 0
[NOTICE] ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/SimpleArea_v0.13-alpha.phar/src/SimpleArea/SimpleArea" at line 671

플레이어가 저 상태에서 땅을 사려고 했을 때 보이는 오류입니다.
[CRITICAL] Unhandled exception executing command '영역구매' in 영역구매: Undefined offset: 0
[NOTICE] ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/SimpleArea_v0.13-alpha.phar/src/SimpleArea/SimpleArea" at line 671

시도해본 방법으로는 일단... 플러그인 초기화, world파일 안의 options.yml과 protects.yml파일을 초기화를 해보았으나 결과는 같았습니다.

터미널 버젼은 1.4.1dev-963  "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)이고요...
같이 돌린 플러그인은 아래와 같습니다.
 EconomyAPI_v2.0.4
 EconomyAirport_v2.0.2
 EconomySell_v2.0.3
 EconomyShop_v2.0.3
 NydusCanal_v1.5-alpha
 SignRegeneration_v1.1-alpha
 SimpleArea_v0.13-alpha
 Trampoline_v1.3
 WorldEditArt_dev_build
 essentialsTP

아, 그리고 처음에 플러그인을 적용할 때도 오류가 났었는 데... 그건 World파일 안의 options.yml과 protects.yml파일을 초기화를 했더니 잘되더라구요...
일단은 맵이랑 각종 관련파일을 다 보내봅니다.... ㅠㅠㅠ
여기 파일입니다...   -->> https://www.dropbox.com/s/p04lg63ekt54izn/%EC%98%A4%EB%A5%98%EB%82%9C%20%EC%A0%84%EC%B2%B4%20%ED%8C%8C%EC%9D%BC%EB%93%A4.zip?dl=0

# 정리해서 #
1. 제가 이해하기론 op가 (/영역생성)으로 땅을 생성한 뒤 (/영역판매)를 해두면 플레이어가 땅을 살 수 있게 땅을 만들 수 있지요.... 맞지요?
2. 판매오류에 대해서...
3. 땅에 번호 매기는 방법....

hm님 항상 감사히 플러그인과 게시글 보고 있고요!! 정말 존경스럽습니당 ㅎㅎ
이번 오류는 제발 해결되길...ㅠㅠ 길게 써서 죄송해요 ㅋㅋㅋ

**Comment by HmHmmHm** [comment]
이전에 심플에리어 플러그인을 사용하셨던 분같습니다.
사용전 plugins/SimpleArea 폴더를 모두삭제해주세요.
언어 설정에서 추가된 내용이 자동으로 변경되지 않고 있네요

**Comment by radic2682** [comment]
삭제했는 데도 같은 오류가 발생해요 ㅠㅠ
그리고 땅 번호 매기는 방법좀 알려주세요

**Comment by HmHmmHm** [comment]
본문을 정확하게 읽어주세요..

1. /영역생성으로 땅을 생성하는 것은 'OP'와 '유저' 모두 가능
2. 확인 중에 있습니다 (이쪽에서 확인이 안됨)
3. 영역번호는 자동으로 매겨집니다

**Comment by HmHmmHm** [comment]
@radic2682  심플에리어 0.14 업데이트되었습니다.
