### ISSUE TITLE
표지판 상점 플러그인

### ISSUE THREAD

**Issue by BakHaS** [if-Team/PMMP-Plugins#5]
표지판 상점플러그인이 좋겠어요.
signshop플러그인을 어떻게 사용해야하
는지 이해가 안가서..쉽고 간단한 상점
플긴이 있음해요!
표지판
1번째줄:[buy]&[sell]
2번째줄:아이템코드(사거나 팔)
3번째줄:얻거나 줄 아이템의 개수
4번째줄:얻거나 주는(잃는)돈의 양
대강 이런식으로요..
부탁드립니다. 그리고 €cono¥플러그인이나
Pocketmoney등의 플러그인과 호환이
되게 해주시면 감사하겠습니다!  꾸벅(_ _)

**Comment by ChalkPE** [comment]
새로 이슈 만들지 마시고 #2번 이슈에 덧글 다세요
