### ISSUE TITLE
CallbackTask를 죽입시다 CallbackTask는 나의 원수

### ISSUE THREAD

**Issue by ChalkPE** [if-Team/PMMP-Plugins#54]
- [x] EntitiesCleaner::onClean [`d20e43a`](https://github.com/if-Team/PMMP-Plugins/commit/d20e43a2a54549462ba82ecc76b02b6413dad425)

- [x] EntitiesCleaner::onMonsterClean [`d20e43a`](https://github.com/if-Team/PMMP-Plugins/commit/d20e43a2a54549462ba82ecc76b02b6413dad425)

- [x] EconomyGamble::EconomyGamble [`0160204`](https://github.com/if-Team/PMMP-Plugins/commit/016020407d09cbfb13ed7a5afd80df918abcbebf)
- [x] CommandDefender::removeQueue [`d20e43a`](https://github.com/if-Team/PMMP-Plugins/commit/d20e43a2a54549462ba82ecc76b02b6413dad425)

- [x] Chatty::Chatty [`541c080`](https://github.com/if-Team/PMMP-Plugins/commit/541c080fa3597958857bbf3ac0a15fb787bc8bdc)

- [x] motdOnline::updateServerName [`ea93272`](https://github.com/if-Team/PMMP-Plugins/commit/ea932728a312eb5eb84d5c2da84d15ae5ab9509e)

- [x] Purge::purgeSchedule [`0160204`](https://github.com/if-Team/PMMP-Plugins/commit/016020407d09cbfb13ed7a5afd80df918abcbebf)
- [x] EDGE\EDGE [`d20e43a`](https://github.com/if-Team/PMMP-Plugins/commit/d20e43a2a54549462ba82ecc76b02b6413dad425)

- [ ] PSYCHOPASS_Dominator::saveExecuteData

- [x] entitiesSave::entitiesSave [`0160204`](https://github.com/if-Team/PMMP-Plugins/commit/016020407d09cbfb13ed7a5afd80df918abcbebf)

**Comment by ns827** [comment]
광속이다!
