### ISSUE TITLE
쓰레기통플러그인

### ISSUE THREAD

**Issue by dotori** [if-Team/PMMP-Plugins#57]
스크립트중에 쓰레기통 스크립트라고 벽을 위로두칸두고 벽앞에 밑에칸에 창고를 설치하고 그위칸에 벽에 첫번째줄에 쓰레기통치고 표지판설치하고 창고안에 템넣고 표지판 누르면 템이 버려지는 스크립트가 있는데 
작동방법은 똑같이 하는 쓰레기통 플러그인 제작가능할까요?

**Comment by ns827** [comment]
#2 

제발.. 개발자들 암걸려요...제발...
