### ISSUE TITLE
Farms 오류

### ISSUE THREAD

**Issue by Xesame** [if-Team/PMMP-Plugins#59]
환경: 안드로이드(베가R3)
버전: 0.11.0 베타빌드 8

오류: 호박을 심었는데 줄기만 자라고 호박은 나오지 않네요... 속도설정에서 속도를 빠르게도 해봤고, 주변에 물도 놓아봣지만 아무 소용도 없었습니다. 수박 또한 마찬가지였습니다. (나머지는 괜찮아요)

항상 감사합니다 hm님

**Comment by HmHmmHm** [comment]
@Xesame Farms 재 코딩 중에 있습니다, 그리고 이슈 띄우지마시고 #1 에서 모아서 쓰시라고 분명히 말씀드렸습니다.
