### ISSUE TITLE
아이템케이스

### ISSUE THREAD

**Issue by childcovo** [if-Team/PMMP-Plugins#6]
아이템케이스부탁드립니다
유리안에 드랍된아이템이 먹어지지않고 계속 전시도있는 그런 플러그인 부탁드려요....

**Comment by HmHmmHm** [comment]
창조경제 플러그인이 기본적으로 지원할겁니다
(다른 이슈칸 만들지말고 에리리포트 페이지랑
위시리스트 페이지만 이용하시기 바랍니다)
