### ISSUE TITLE
SimpleArea 오류(꼭 읽어주세요 이거때매 카페가..)

### ISSUE THREAD

**Issue by Xesame** [if-Team/PMMP-Plugins#68]
안녕하세요 xesame입니다

우선 님이만드신 플러그인 아주 감사하게

쓰고 있다는 점부터 밝히겠습니다

+오류 플러그인명: Simplearea 0_15_9

+오류 내용: 콘솔에 Callback#뭐 이런게뜹니다.. 그거뜬거 확인하고 서버에 들어가면 항상 오류가 걸리는걸 확인했습니다(스샷을 확인해주세요 이메일로 보내드렸습니다)

+사용중인 Pocketmine-MP.phar 버전: #1139(님이 배포하신 버전입니다.) API12

+사용 환경: 안드로이드 베가 R3 (RAM은 1G)
↑혹시몰라서 적어봅니다

+크래시덤프(Callback 이거 엄청나게 떴습니다)는 이메일로 보내드렸으니 확인부탁드리겠습니다

혹시 전에 말씀하셨던 SimpleAuth플러그인과의 충돌인가요?(현재 Simpleauth는 제가 포럼에서 직접 다운받아 한글화해서 사용 중입니다) 아니면 플러그인 자체의 오류인지, 혹은 콘솔 오류인지... 알지를 모르니까 답답하기만 하네요.. 플러그인 오류라면 조속히 고쳐주시기 바랍니다.

※걱정마세요 ! 설정미숙 이런건 없었습니다

플러그인 만들어주신거 다시한번 감사드립니다.

바쁘시겠지만, 부탁드릴게요 !

**Comment by ns827** [comment]
#1 제발... 이런데 두고 어디다 씁니까
