### ISSUE TITLE
플러그인 오류..

### ISSUE THREAD

**Issue by jangmur** [if-Team/PMMP-Plugins#71]
나이스더스커널..인가요?
그 플러그인 worlds 폴더에 sag1 로 넣었는데
포탈하면 sag1을 찾을수 없다하네요.

또 포탈을 하나 만들면 채팅이 안되고
채팅을 칠시 뭔 chat어쩌주저쩌구 채팅이 대신 출력됩니다.

**Comment by HmHmmHm** [comment]
본문의 댓글들만 보셨어도 아실거같은데
pocketmine.yml 에서 멀티월드를 인식시켜주셔야하고
(DPMMP에서는 멀티월드가 안된다는 얘기도 있습니다)
또한 나이더스커널엔 현재 두버전이 있습니다.
채팅비포함 버전으로 이용해주시면 됩니다.
