### ISSUE TITLE
무제한 광산 명령어 무반응

### ISSUE THREAD

**Issue by DiamondBlock** [if-Team/PMMP-Plugins#73]
0. Pocketmine 버전: 1.5 Dev.1238
1. 플러그인 버전: 무제한광산 0.6 버전
2. 에러 발생 상황: 에러인지는 모르겠지만 이 플러그인에 관한 명령어를 쓰면 아무 반응이 없다.
3. 에러의 주 내용: 명령어를 쓰면 반응이 없는 문제가 있다.
4. 크래시덤프 전송여부: N 크래쉬 덤브 파일이 나오는것은 아닙니다.

**Comment by ChalkPE** [comment]
#1
