### ISSUE TITLE
나이더스커널플러그인

### ISSUE THREAD

**Issue by MaInYee** [if-Team/PMMP-Plugins#76]
0. Pocketmine 버전:1.5dev-1240
 1. 플러그인 버전: 나이더스커널 1.5 알파
2. 에러 발생 상황:제가 상점에 워프포인트를 만들었는데 갑자기 모든 채팅이 [ 상점 ] chat.type.text 라고뜸3. 에러의 주 내용: 위와 같음
4. 크래시덤프 전송여부: N 크래시 덤프가 안뜸

**Comment by ChalkPE** [comment]
#1

**Comment by ns827** [comment]
***에러 리포트는 #1 로 가셔서 써야 합니다. 제발 지켜주세요***
