### ISSUE TITLE
GoAwayAnna

### ISSUE THREAD

**Issue by peepzandmeepz** [if-Team/PMMP-Plugins#77]
Hi there!

The plugin "GoAwayAnna" seems to not be compatible with the newer versions of Pocketmine after they updated the network protocols. 

Unsure if this project is still active or not so I would just make this to report that it currently isn't working. :)

**Comment by HmHmmHm** [comment]
ok, i'll check, it's need a little time
(Because my university exam period..)

**Comment by peepzandmeepz** [comment]
Ok, thanks!
