### ISSUE TITLE
따로따로 광산?!

### ISSUE THREAD

**Issue by KNE0012** [if-Team/PMMP-Plugins#80]
마을전쟁 같은거 할때 광산을 따로 설정하는것
EX) /무제한 광산 을 할경우 
한광산은 돌만 나오고 또 한광산은
철과 금 돌 만 나오게 등등 만들어주시면 감사해요

항상 그냥 /무제한 광산 하면 똑같이 평등하게 나와서
약간 힘드네요...ㅠ😱

**Comment by ns827** [comment]
#2 제발 눈이 있으면 한번만 읽어봅시다

**Comment by HmHmmHm** [comment]
흥미로운 주제인데 코딩이 좀 복잡해질것같네요,
일단 제가 별도로 TODO에 넣어놓겠습니다.
