### ISSUE TITLE
pmmp좀비서바이벌플러그인

### ISSUE THREAD

**Issue by ehddls** [if-Team/PMMP-Plugins#82]
/포탈을 치면 정면에 3×3포탈이 만들어져서 10분마다 들어갈수있고(10분안에 게임이끗나야됨) (총은 랜덤무기전쟁 플러그인 총사용)들어가면 여러가지 맵이연결되 있어서 그중 포탈을 제일먼저 들어간 사람이 있는곳으로 포탈을들어가면 그쪽으로가게되고 총이 1개씩기본지급되고 30초뒤 숙주좀비(플래이어)가 소환되고 손으로 때릴시 점염되고 총은 플래이어끼리는 안맞고 좀비만 맞는다 그리고총은여러게가 있어서 무기상점에서 살수있고 아이템이 버려지지않고 /쓰래기통 이라는명령어를치면 칸이나오는데 버리고싶은것을 치면 쓰래기통에 버려지고 10초뒤 없어진다 /창고명령어 를치면 칸이 여러게 나오고 지금은 쓸일이없는것을 넣을수있고 게임이 끊나면 스폰으로 자동티피 올되고  전브다 감염되면 다이아몬드 3개가전체 나누어주고 생존자가있으면 생존자들만 다이아 2개를받고 인벤세이브가 되는플러그인돔 만들어즈시면 안되나요?...

**Comment by ns827** [comment]
말이 쉽지 저거 간단한 플긴이 아닙니다만
그리고 플긴 위시리스트는 #2 로 가라고 몇번을 말합니까
