### ISSUE TITLE
좀비서바이벌 플러그인

### ISSUE THREAD

**Issue by ehddls** [if-Team/PMMP-Plugins#83]
pocketmine-mp 버전: 1.5
플러그인: /포탈 명령어를 친뒤 모서리 2곳을터치하면 포탈이생성되고 5분마다 게임에들어갈수있다
포탈에들어가면 9곳의 좀비서바이벌 맵에 순서대로 들어갈수있다 30초뒤에는 숙주좀비가 생기고 게임이
시작된다. (맵에는 생존자가 숨을곳이랑 공격하기좋은곳 몇둔데가 있어야됨) 시작되면 신속 2가 붙고 저항
이생긴다. (그리고 게임엔 랜덤무기전쟁 플러그인이랑 연합해야됨) 그리고 기본지급으로 통일된하나의 
총이 지급된다. 그리고 생존자끼리는 총에맞지않고 좀비들만 총에맞는다 좀비가 플래이어를 감영시킬때에는
레드스톤으로 상대를 때리면 좀비가 된다.  전부 좀비가되면 좀비들한테 다이아3개 생존자가있으면 다이아
2개(포탈에들어간 사람만) 총상점이있어서 랜덤무기전쟁 총을살수있다
/쓰레기통 명령어를치면 칸이1개 나와서 인벤에 있는물간을 터치하면 10초뒤 없어진다.
/창고 명령어를치면 인벤토리랑 똑같이 나와서 터치하면 보관할수있다.
인벤세이브가 되야한다*
*이런플러그인좀 개발부탁드립니다*

**Comment by ns827** [comment]
제가 분명히 #82 에서 #2 에 작성하라고 분명히 말씀드렸는데요. 이슈 닫으면 그냥 새로 연다는 발상은 어디서 주워온 건지 모르겠지만 여기는 제제 시스템이 없어보여서 이렇게 규정 어기고 돌아다니시는 건가요? 분명 MK에서 오셨다면 MK에 관련 가이드가 있었을 테고 거기에 맞춰서 하면 제대로 된 답을 얻으실 텐데 뭐 하시는 겁니까. ***개발자가 빙다리 핫바지로 보이십니까?*** 개발자는 무언가 아이디어 툭 던져주면 윙윙 돌아가면서 키보드로 코딩해준 다음에 친절하게 사용법과 세팅 가이드까지 작성해서 올려주는 *호구 내지 로봇*이 아닙니다. 제발 개념이 1%라도 남아 있다면 [이런 데서](http://cafeptthumb1.phinf.naver.net/20150511_198/hmkuak_1431353408067bAN7o_PNG/%C1%A6%B8%F1_%BE%F8%C0%BD-1.png?type=w740) 가이드라인 한번만 읽어보시고 #2 로 가셔서 위시리스트 작성하세요. 이런데서 쓰셨다가 재수 없게 저처럼 가끔씩 멘탈 나가 키보드 잡고 이런 글 싸지르고 있는 개발자에게 욕 처듣기 싫으시면요.
