### ISSUE TITLE
무제한 광산오류(양식지켜서 재작성함.)

### ISSUE THREAD

**Issue by misoAllo** [if-Team/PMMP-Plugins#87]
0. Pocketmine 버전: 1.5 (1.12.0)
1. 플러그인 버전: 무제한 광산 0.6
2. 에러 발생 상황: 명령어 /무제한 쳤는데 아무반응없음.
3. 에러의 주 내용: 명령어를 칠시 아무반응이 없다. 
4. 크래시덤프 전송여부: 크래시 덤프가 아니다..

**Comment by ns827** [comment]
#1 로 가주세요
