### ISSUE TITLE
무제한 광산 오류

### ISSUE THREAD

**Issue by misoAllo** [if-Team/PMMP-Plugins#88]
0. Pocketmine 버전: 모바일 이구요. 1.5 Dev 1254
1. 플러그인 버전: 무제한 광산 0.6 버전
2. 에러 발생 상황: 무제항 플긘 명령어 반응이없네요.
3. 에러의 주 내용: 무제한 광산 명령어에 오류가있으며 
채팅창에 /무제한 and 그외 무제한 플긘 쳐도 반응이없네요.
4. 크래시덤프 : Y (전송중 이라네요.)

**Comment by ChalkPE** [comment]
#1

**Comment by HmHmmHm** [comment]
이 레포에서 밴처리되었음을 알려드립니다.
