### ISSUE TITLE
채팅금지플러그인이요!

### ISSUE THREAD

**Issue by qaw13** [if-Team/PMMP-Plugins#9]
포럼에있는건다안되가지구..  command: /mute 닉네임(해당유저를벙어리시킵니다)
/unmute 닉네임 (해당유저벙어리를풀어줍니다)
/allmute(OP외에모든사람채팅을차단시킵니다)
/allunmute (채팅차단을해제합니다)
이런플러그인한번써보고싶어요(ToT)

**Comment by ns827** [comment]
위시리스트에 작성하셔야 합니다.
