### ISSUE TITLE
심플오스 업데잍  희망사항

### ISSUE THREAD

**Issue by dkdkdk8798** [if-Team/PMMP-Plugins#90]
이번에는 부계를 못만들게 막는건 없나요 몇달전부터 생각을 했는데 본계 만들면 부계를 못만들겠금 업데이트 해주세요...

**Comment by ns827** [comment]
이슈 만들어 놓고 close시키는 건 의견 제출해놓고 번번히 취소하는 것이랑 똑같습니다. 그냥 놔두시면 관리자들이 알아서 close하던지 open한 상태로 놓습니다.

그리고 아이디어 제시는 #2
