### ISSUE TITLE
심플오스 업데이트 희망사항

### ISSUE THREAD

**Issue by dkdkdk8798** [if-Team/PMMP-Plugins#91]
이번에는 부계를 못만들게 막는건 없나요 몇달전부터 생각을 했는데 본계 만들면 부계를 못만들겠금 업데이트 해주세요...

**Comment by 64FF00** [comment]
심플오스는 이프팀이 만든거 아니라고요 ㅡㅡ

**Comment by ns827** [comment]
#2 로 가시라고 말씀드렸을텐데요. 한 번도 안 읽어 보셨나요?

* 개발자는 남이 부탁하면 다 들어주는 만능천사가 아닙니다. 부탁을 할려면 최소한 양식과 그에 맞는 절차를 지키세요. 제발. *

**Comment by HmHmmHm** [comment]
@dkdkdk8798 이 레포에서 차단되었음을 알려드립니다.
