### ISSUE TITLE
아이디어] 마인팜

### ISSUE THREAD

**Issue by nature3917** [if-Team/PMMP-Plugins#92]
/myfarm 칠시 자기의 마인 팜에 갑니다.
/farm buy 칠시 마인팜을 구입합니다 (가격은 플러그인으로 수정 가능하며 좋겠어요...)
/farm invite (닉네임) 이건...수락기능도 있으면 좋을텐데...뭐라 설명을 못하겠네요 ㅠ.ㅜ
마인팜은 리스폰에서 월드이동 같은(?) 그런 (플러그인 안에서 월드가 생기는(?) ) 좋겠습니다.
이 플러그인 제작이 어려우시면 아이디어를 안 받으셔도 됩니다...

**Comment by ChalkPE** [comment]
#2
