### ISSUE TITLE
플레이어 관리 플러그인(업데이트)

### ISSUE THREAD

**Issue by Sudden620** [if-Team/PMMP-Plugins#93]
/mute <닉네임> 해당 플레이어의 채팅을 맊습니다
/move <닉네임> 해당 플를이어를 움직이지 못하게 합니다
/pvp     <닉네임> 해당 플레이의 pvp 맊습니다
그냥 기존에 있던 플레이어 관리 플러그인을 업데이트 시키는 겁니다
기존에 있던건 allplayer 이라면
이 플러그인은 특정 플레이어만 제어 하는 겁니다

**Comment by HmHmmHm** [comment]
이슈를 새로 여시면 안됩니다!
에러리포트는 #1 로
위시리스트는 #2 로!
한번 더 위반시 레포에서 블락처리 예정입니다.
