### ISSUE TITLE
서버 관리 OP아이피반응 

### ISSUE THREAD

**Issue by IUL** [if-Team/PMMP-Plugins#96]
OP들의 게인아이피에 반응해서 OP권한이생기고 안생기고하는겁니다
예)ABC라는OP가있는대 아이피가 1234 서버접속 OP ON
비정상유저 가 ABC라는op의 비밀번호를알아서접속 아이피가 1235 서버접속 OP OFF.ㅇㅅㅇ

**Comment by HmHmmHm** [comment]
- [ ] SuperUser 플러그인 추가
/su <서버암호> 명령어 사용 시 해당 유저 OP처리

**Comment by IUL** [comment]
오오.빠르시네욥.감사함니당 ㅇㅅㅇ!
