### ISSUE TITLE
GoAwayAnna - Pocketmine "Bleeding" Builds incompatibility

### ISSUE THREAD

**Issue by peepzandmeepz** [if-Team/PMMP-Plugins#98]
Hello there!

I am unsure if I need to report this (let alone if I can). However, I wanted to notify you that GoAwayAnna does not work with the new "Bleeding" builds (0.12.1 alpha builds) of PocketMine. I don't have any error messages or anything.

Thanks and sorry if I reported this incorrectly..

**Comment by cr0sh** [comment]
That's because PocketMine 1.6 uses backwards-incompatible API 2.0.0.

http://forums.pocketmine.net/threads/upcoming-changes-in-api-and-php7.9991/

I think @HmHmmHm will fix after bleeding build is stabilized.

**Comment by HmHmmHm** [comment]
Don't  worry!
I'll apply API 2.0.0 for all the plug-in '~'

**Comment by MuhunKim** [comment]
Close Issue
